# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-08-14 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
