# Generated by Django 3.2.6 on 2021-08-20 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Order'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='staff',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
